name: pycurious
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.13
    - pip
    - numpy
    - scipy
    - pytest
    # Optional dependencies
    - jupyter
    - matplotlib
    - pyproj
    - cartopy
    - netcdf4
    - requests
