FROM alpine:edge

LABEL maintainer="brmather1@gmail.com"
LABEL repo="https://github.com/brmather/pycurious"

# Install things
RUN apk add --update --no-cache \
    gcc \
    g++ \
    gfortran \
    build-base \
    linux-headers \
    python3-dev \
    py3-pip \
    py3-numpy \
    py3-scipy \
    py3-zmq \
    cmake \
    curl \
    wget \
    tini \
    libzmq \
    zlib-dev \
    musl-dev \
    freetype-dev \
    libpng-dev \
    libxml2-dev \
    openblas-dev

RUN echo "http://mirror.leaseweb.com/alpine/edge/testing" >> /etc/apk/repositories
RUN apk add --update --no-cache \
    geos-dev \
    proj4-dev

RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories
RUN apk add --update --no-cache \
    libressl2.7-libcrypto \
    gdal-dev


RUN ln -s /usr/include/locale.h /usr/include/xlocale.h
RUN python3 -m pip install --no-cache-dir --upgrade pip && \
    python3 -m pip install --no-cache-dir --upgrade --force-reinstall numpy scipy && \
    python3 -m pip install --no-cache-dir setuptools wheel Cython && \
    python3 -m pip install --no-cache-dir \
    packaging \
    gdal \
    jupyter \
    tornado \
    pyepsg \
    cartopy && \
    python3 -m pip install --no-cache-dir matplotlib && \
    python3 -m pip install --no-cache-dir --upgrade --ignore-installed pyzmq

# expose notebook port
EXPOSE 8888


# add a notebook profile
RUN mkdir -p -m 700 /root/.jupyter/ && \
    echo "c.NotebookApp.ip = '0.0.0.0'" >> /root/.jupyter/jupyter_notebook_config.py && \
    echo "c.NotebookApp.token = ''" >> /root/.jupyter/jupyter_notebook_config.py


RUN addgroup jovyan && \
    adduser -D jovyan -G jovyan

WORKDIR /home/jovyan
RUN chown -R jovyan:jovyan /home/jovyan
USER jovyan


VOLUME /home/jovyan/$NB_DIR/user_data


ENTRYPOINT ["/sbin/tini", "--"]

# launch notebook
# CMD scripts/run-jupyter.sh
CMD ["jupyter", "notebook", "--ip='0.0.0.0'", "--NotebookApp.token='' ", "--no-browser"]